### ISSUE TITLE
Ensure import paths are correct for blocks, and get registration helper working.

### ISSUE THREAD

**Issue by mrobit** [anchour/wordpress-base-theme#78]
In [`resources/scripts/blocks/register-blocks.js`](https://github.com/anchour/wordpress-base-theme/blob/main/resources/scripts/blocks/register-blocks.js)

`./util/helper` doesn't exist and looks like it was pulled from the coblocks plugin. Can we copy the code from coblocks to the theme? 

Additionally, the paths for the blocks are incorrect – you're already in the blocks directory, so just omit `blocks` from the import.

**Comment by rpmcguire18** [comment]
Fixed with the push of the body block
